### PR TITLE
Keep track of the handle of the first window. Fixes #2805.

### LINKED ISSUE #2805: IE9 sucks at switching windows
We are seeing a lot [1] of test failures where
- it looks like we've logged into 123done/myfavoritebeer successfully
- IE9 cannot find the logged-in node
- the raw selenium log indicates that the element wasn't found as part of a NoSuchWindowException

My guess, based on this, is that IE9 has some bizarro way of sorting handles when it stores them internally. Either that, or it puts the newest window at the 0th, not the nth, spot in the window_handles array, and we only sometimes see this error because it's a race between browser.wwin() switching windows, and the dialog closing, reducing the length of window_handles to 1.

Here's an example of an error log snippet (full log is here [2]) that shows the element lookup failure as the message inside a NoSuchWindowException:

```
15:48:36.094 ERROR - Unexpected exception during findElement
org.openqa.selenium.NoSuchWindowException: Unable to find element with css selector == #emailList .email (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 20.01 seconds
```

Either we manually store the base window handle in every test (since every test uses the dialog and switches back to parent window at some point), or we find a clever but robust way to do this behind the scenes. One trick that could work: assign the topmost window handle when you setup the browser, then, when someone calls wwin() without arguments, pass in the parent window handle by default, instead of assuming the 0th window in the window_handles array is the right one. This is just a guess.

[1] https://gist.github.com/4173166
[2] https://saucelabs.com/jobs/7e772c3b8ebb479186a6bc3fcae657e6/selenium-server.log

### PR DESCRIPTION
**Pull request by jaredhirsch**
See #2805 for discussion.

Rather than track the current window as we switch from window to window during a session, I think we can get away with just grabbing a reference to the first window created at the start of a session--that'll always (I think?) be the one we want when the dialog is gone.

### CODE REVIEW

File: automation-tests/lib/wd-extensions.js [hunk 1]
```diff
@@ -153,7 +161,7 @@ wd.prototype.wwin = function(opts, cb) {
     cb = arguments[0];
     self.windowHandles(function(err, handles) {
       if (err) return cb(err);
-      self.window(handles[0], function(err) { cb(err); }); // fire cb whether err is defined or not
+      self.window(browser._parentWindow, function(err) { cb(err); }); // fire cb whether err is defined or not
```
Comment (shane-tomlinson) [inline automation-tests/lib/wd-extensions.js]: browser does not exist in this context, _parentWindow is on self at this point. This is causing a silent failure where all of the tests appear to pass but where all the tests continue running on sauce.

Comment (shane-tomlinson) [inline automation-tests/lib/wd-extensions.js]: Secondly, since the callback to self.window only calls cb with the err, can we replace the entire `function(err) { cb(err); }` with cb.

File: automation-tests/lib/wd-extensions.js [hunk 2]
```diff
@@ -77,7 +77,14 @@ wd.prototype.newSession = function(opts, cb) {
     // procedures like find_element to succeed (we'll actually wait on the
     // *server* side for an element to become visible).  Having this be
     // the same as the global default timeout is interesting.
-    browser.setImplicitWaitTimeout(timeouts.DEFAULT_TIMEOUT_MS, cb);
+    browser.setImplicitWaitTimeout(timeouts.DEFAULT_TIMEOUT_MS, function(err) {
```
Comment (shane-tomlinson) [inline automation-tests/lib/wd-extensions.js]: We should standardize on `browser` or `self`, but not both. Having two names is probably what caused this problem.

Comment (shane-tomlinson) [inline automation-tests/lib/wd-extensions.js]: issue #2817 opened for this. PR #2818 fixes this replacing all `browser` instances with `self`.

Comment (jaredhirsch) [inline automation-tests/lib/wd-extensions.js]: Argh. This is my goof. I blatantly ignored the use of self throughout.

**Comment by jaredhirsch** [comment]
One minor conflict made it a non-fast forward merge, merged origin into topic branch.

If this seems unclean I can remove that last commit and just merge topic branch into dev, resolving the conflict at that time instead.
