### PR TITLE
Fix for users who are unable to sign out.

### LINKED ISSUE #3386: Users cannot log out
We're seeing that calling `navigator.id.logout()` no longer logs the user out. You can see it for yourself:
1. Visit marketplace-dev.allizom.org
2. Sign in with Persona
3. Sign out (hover over the gear in the upper right)
4. Refresh the page

We're calling `navigator.id.watch()` with a blank string for the email and on sign out we're calling `navigator.id.logout()`, and yet Persona still magically fires `onlogin` with an assertion when the page loads.

### PR DESCRIPTION
**Pull request by shane-tomlinson**
@seanmonstar, @callahad, @jrgm - This is for a hotfix of prod. Review would be fantastic.

When upgrading localStorage from loggedIn to use the site namespace, I failed to remove the old loggedIn namespace, making it so users would sign out, refresh the page, and be signed in again.

fixes #3386

### CODE REVIEW

File: resources/static/common/js/storage.js [hunk 1]
```diff
@@ -44,6 +44,7 @@ BrowserID.Storage = (function() {
     for (var site in allInfo) {
       siteSet(site, "logged_in", allInfo[site]);
     }
+    storage.removeItem("loggedIn");
```
Comment (shane-tomlinson) [inline resources/static/common/js/storage.js:47]: This is the key line - this removes the loggedIn namespace after upgrading.

File: resources/static/common/js/storage.js [hunk 2]
```diff
@@ -595,5 +596,13 @@ BrowserID.Storage = (function() {
      * @method setDefaultValues
      */
     setDefaultValues: setDefaultValues
+    // BEGIN TRANSITION CODE
+    /**
+     * Upgrade the site->user logged in info from the loggedIn namespace to be
+     * under the site namespace.
+     */
+    ,
+    upgradeLoggedInInfo: upgradeLoggedInInfo
```
Comment (shane-tomlinson) [inline resources/static/common/js/storage.js:605]: I surfaced this function to be able to test it.

**Comment by seanmonstar** [comment]
r+, waiting on travis to complete

**Comment by jrgm** [comment]
@shane-tomlinson - Thanks for the fix! (p.s., we'll need this also on train-2013.05.08 and dev, of course).
