### PR TITLE
When showing the authentication screen, make sure to hide the warning screens

### LINKED ISSUE #2839: Cancel button non-functional when primary IDP is broken
reproduced by the `broken-primary.js` automated test, currently in the `primary-automation-tests` branch.

### PR DESCRIPTION
**Pull request by shane-tomlinson**
@ozten - mind reviewing this?
- For clarity, rename renderDialog to renderForm.

fixes #2839

### CODE REVIEW

File: resources/static/common/js/modules/page_module.js [hunk 1]
```diff
@@ -79,6 +77,17 @@ BrowserID.Modules.PageModule = (function() {
...
 
     /**
+     * Hides the warning screens
+     * @method hideWarningScreens
+     */
+    hideWarningScreens: function() {
+      var self=this;
+      self.hideWait();
+      self.hideError();
+      self.hideDelay();
```
Comment (ozten) [inline resources/static/common/js/modules/page_module.js:87]: Ah, I see. Awesome.

File: resources/static/dialog/js/modules/verify_primary_user.js [hunk 2]
```diff
@@ -60,7 +60,7 @@ BrowserID.Modules.VerifyPrimaryUser = (function() {
 
       user.addressInfo(email, function onSuccess(info) {
         if (showsPrimaryTransition(info.state)) {
-          self.renderDialog("verify_primary_user", {
+          self.renderForm("verify_primary_user", {
```
Comment (ozten) [inline resources/static/dialog/js/modules/verify_primary_user.js:63]: Yes, I think this is a better name.

File: resources/static/test/cases/common/js/modules/page_module.js [hunk 3]
```diff
@@ -8,8 +8,33 @@
       bodyTemplate = "test_template_with_input",
       waitTemplate = "wait",
       bid = BrowserID,
+      testHelpers = bid.TestHelpers,
+      testElementExists = testHelpers.testElementExists,
+      testElementDoesNotExist = testHelpers.testElementDoesNotExist,
+      testElementFocused = testHelpers.testElementFocused,
+      FORM_CONTENTS_SELECTOR = "#formWrap .contents",
```
Comment (ozten) [inline resources/static/test/cases/common/js/modules/page_module.js:15]: Not for this pull request, but it would be great to re-use these constants in tests from the production code, so there is only one place to update them.

File: resources/static/test/cases/common/js/modules/page_module.js [hunk 4]
```diff
@@ -30,49 +55,52 @@
   test("page controller with no template causes no side effects", function() {
     createController();
 
-    var html = el.find("#formWrap .contents").html();
+    var html = el.find(FORM_CONTENTS_SELECTOR).html();
     equal(html, "", "with no template specified, no text is loaded");
 
-    html = el.find("#wait .contents").html();
+    html = el.find(WAIT_CONTENTS_SELECTOR).html();
```
Comment (ozten) [inline resources/static/test/cases/common/js/modules/page_module.js:61]: Nice cleanup.

**Comment by ozten** [comment]
I'm going to merge this to dev. I'm going to hold off on a hot patch to the current train. I'll put this pull request into https://id.etherpad.mozilla.org/primary-transition-ux-swarm for hot patch candidates.

File: resources/static/test/cases/common/js/modules/page_module.js (hunk 3 above)
Comment (shane-tomlinson) [inline resources/static/test/cases/common/js/modules/page_module.js:15]: Emphatic +1. I was wondering if anybody else would have found value in abstracting those out for general re-use.

**Comment by seanmonstar** [comment]
@shane-tomlinson yessss!!!!
