### PR TITLE
Supress the "invalid json" error messages in the unit tests.

### LINKED ISSUE #3290: frontend tests: `invalid options string: {invalid_json:}` in console
Noticed this. @jedp, @shane-tomlinson will know better about what it means.

```
$ git symbolic-ref --short -q HEAD | perl -pe 's/\n//'; echo -n ' - '; git rev-parse --short HEAD
dev - 11fdd08

$ phantomjs --version
1.9.0

$ node --version
v0.8.17

$ uname -a
Darwin jmorrison.local 11.4.2 Darwin Kernel Version 11.4.2: Thu Aug 23 16:25:48 PDT 2012; root:xnu-1699.32.7~1/RELEASE_X86_64 x86_64

$ WHAT_TESTS=front npm test

> browserid@1.0.0-b1 test /Users/jmorrison/github/mozilla/browserid
> ./scripts/test

>>> Now Running: Front end unit tests under PhantomJS
· · · · router (39394): info: forwarding request: /common/js/error-messages.js -> http://127.0.0.1:10010/common/js/error-messages.js
currently unable to focus elements, focus check skipped - try focusing the unit test page

invalid options string: {invalid_json:}
invalid options string: {invalid_json:}

currently unable to focus elements, focus check skipped - try focusing the unit test page
currently unable to focus elements, focus check skipped - try focusing the unit test page
currently unable to focus elements, focus check skipped - try focusing the unit test page
currently unable to focus elements, focus check skipped - try focusing the unit test page
'waitFor()' finished in 53288ms.
Tests completed in 53117 milliseconds.
1622 tests of 1622 passed, 0 failed.
· · · ✓ OK » 7 honored (58.192s)
```

### PR DESCRIPTION
**Pull request by shane-tomlinson**
@jedp - could you review this one?

fixes #3290

### CODE REVIEW

File: resources/static/dialog/js/misc/internal_api.js [hunk 1]
```diff
@@ -81,7 +81,9 @@
    * @param {object} options.  See options block for navigator.id.get.
    * options.silent defaults to false.
    */
-  internal.get = function(origin, callback, options) {
+  internal.get = function(origin, callback, options, externalLog) {
```
Comment (jedp) [inline resources/static/dialog/js/misc/internal_api.js:84]: That's great.  Thanks for adding that.  I can use that right away in b2g :)

File: resources/static/test/cases/dialog/js/misc/internal_api.js [hunk 2]
```diff
@@ -33,6 +33,10 @@
     }
   };
 
+  function suppressLog(msg) {
```
Comment (jedp) [inline resources/static/test/cases/dialog/js/misc/internal_api.js:36]: totally.

**Comment by jedp** [comment]
Ship it!
